plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.personal.audioapp"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.personal.audioapp"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        // Used by the AppAuth redirect activity declaration in the manifest:
        // <data android:scheme="${appAuthRedirectScheme}" />
        manifestPlaceholders["appAuthRedirectScheme"] = "com.personal.audioapp"
    }

    // ------------------------------------------------------------------
    // The keystore only exists inside CI (generated by keytool) or after
    // the user downloads the "keystore" artifact. A local machine with no
    // JDK/Android Studio simply falls back to AGP's built-in debug key.
    // ------------------------------------------------------------------
    signingConfigs {
        if (file("keystore.jks").exists()) {
            getByName("debug") {
                storeFile = file("keystore.jks")
                storePassword = "123456"
                keyAlias = "my-alias"
                keyPassword = "123456"
            }
        }
    }

    buildTypes {
        getByName("debug") {
            isMinifyEnabled = false
            if (file("keystore.jks").exists()) {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            if (file("keystore.jks").exists()) {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += setOf(
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/LICENSE.md",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt",
                "META-INF/NOTICE.md",
                "META-INF/AL2.0",
                "META-INF/LGPL2.1",
                "META-INF/INDEX.LIST"
            )
        }
    }

    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }
}

dependencies {
    // ---------------- Jetpack Compose ----------------
    implementation(platform("androidx.compose:compose-bom:2024.10.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    // Version managed by the Compose BOM above; needed for Icons.Filled.*
    implementation("androidx.compose.material:material-icons-core")
    debugImplementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.activity:activity-compose:1.9.3")

    // ---------------- Room ----------------
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // ---------------- WorkManager ----------------
    implementation("androidx.work:work-runtime-ktx:2.9.1")

    // ---------------- Auth (AppAuth) ----------------
    implementation("net.openid:appauth:0.11.1")

    // ---------------- Network (Google Drive REST) ----------------
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // ---------------- Coroutines ----------------
    // Direct dependency because AuthRepository uses suspendCancellableCoroutine.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // ---------------- Secure storage ----------------
    implementation("androidx.security:security-crypto:1.1.0-alpha06")

    // ---------------- Audio compression ----------------
    // NOTE: the original com.arthenica FFmpeg kit was removed from Maven
    // Central, so the maintained fork is used instead.
    implementation("dev.ffmpegkit-maintained:ffmpeg-kit-audio:8.1.7")

    // ---------------- Kotlin stdlib / coroutines ----------------
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.21")
}
